# https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

Metrics/AbcSize:
  Enabled: true
  Max: 22


Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Max: 120
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/StructInheritance:
  Enabled: false